import { type NextPage } from "next";
import Head from "next/head";
import { Heading, Flex, Box, Spacer } from "@chakra-ui/react";
import RoomCard from "../components/RoomCard";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Link href="/notice">
          <Box className="rounded border-b bg-gradient-to-l from-gray-100 via-gray-200 to-gray-300 p-8">
            <Heading size="3xl">会議室予約サービスへようこそ！</Heading>
            <Spacer h={10} />
            <Heading size="lg">
              ここをクリックし、最新のお知らせを確認しましょう。
            </Heading>
          </Box>
        </Link>
        <Spacer h={10} />
        <Heading size="xl" textAlign="center">
          会議室状況
        </Heading>
        <Flex className="flex-wrap justify-center gap-4 p-20">
          <RoomCard />
          <RoomCard />
          <RoomCard />
          <RoomCard />
          <RoomCard />
        </Flex>
      </Box>
    </>
  );
};

export default Home;
